name: GitLeaks
on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: gitleaks
    uses: ArcadiaPower/gitleaks-workflow/.github/workflows/gitleaksv2.yaml@secret
    secrets: inherit
