name: GitLeaks
on:
  pull_request:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: gitleaks
    uses: Urjanet/gitleaks-workflow/.github/workflows/gitleaks.yaml@f1e2e6f3b3190499b6ad214d3cc55fca908239ec
    secrets: inherit
